# Generated by Django 5.2 on 2025-05-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_cartitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image_code',
            field=models.CharField(default='pro1', help_text='Reference to static image (pro1, pro2, etc)', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='image_code_alt1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_code_alt2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
