# Generated by Django 5.2 on 2025-05-18 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_product_image_product_image_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_code_alt1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_code_alt2',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category'),
        ),
    ]
